#TODO fix config.ssh.shell...
##### https://dev.to/mattdark/using-docker-as-provider-for-vagrant-10me
### https://stackoverflow.com/questions/73748878/how-to-run-docker-in-docker-in-an-alpine-container-as-a-non-root-user

# adapted for alpine
#FROM alpine
#FROM docker.io/docker:18.06-dind
FROM docker.io/docker:24.0-dind

ARG USER=vagrant
##ARG DOCKER_GID="$(stat -c '%g' ${DOCKER_SOCKET})"
##ARG DOCKER_GID="$(stat -c '%g' /var/run/docker.sock)"
#ARG DOCKER_GID
### set argument with default value
ARG DOCKER_GID=121
ENV HOME /home/$USER


ENV TZ=America/Mexico_City
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

USER root

RUN apk update
#?RUN apk add --update \
RUN apk add \
  sudo \
  iproute2 \
  openssh

### add user vagrant
RUN addgroup -S $USER \
  && adduser -S $USER -G $USER -s /bin/bash \
  && echo -n "$USER:$USER" | chpasswd
RUN addgroup -S sudo \
  && addgroup $USER sudo
RUN mkdir -p /etc/sudoers.d \
  && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
  && chmod 0440 /etc/sudoers.d/$USER

RUN mkdir -p /home/$USER/.ssh \
  && chmod 700 /home/$USER/.ssh
###  This default 'insecure' key will be automatically replaced later when you initialize your virtual environment
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > /home/$USER/.ssh/authorized_keys
RUN chmod 600 /home/$USER/.ssh/authorized_keys
RUN chown -R $USER:$USER /home/$USER/.ssh

RUN sed -i -e 's/Defaults.*requiretty/#&/' /etc/sudoers
RUN sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config
### if threre is no systemd or service
RUN mkdir /var/run/sshd

### alpine specific
RUN ssh-keygen -A
### Vagrant fails to replace insecure ssh key if shell is alpine default's "ash"
RUN apk add bash

#??
RUN apk add --no-cache openssh-client

### add vagrant user to docker group
#RUN delgroup ping
#RUN delgroup $(grep $DOCKER_GID /etc/group | cut -d: -f1)
#RUN delgroup docker
#RUN groupmod --gid $DOCKER_GID docker

### make 'docker' group with GID=host docker socket gid
RUN addgroup -S -g "$DOCKER_GID" docker \
  && addgroup $USER docker

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
